### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by zorn-v** [atom/ide-php#149]
![изображение](https://user-images.githubusercontent.com/12619075/71474403-f0ad9f00-2826-11ea-9ef4-1d3c7d646fa5.png)

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
