### ISSUE TITLE
IDE-PHP and PHP 7.4 not working

### ISSUE THREAD

**Issue by orukaz** [atom/ide-php#150]
I installed PHP 7.4 to my server and if I activate "atom/ide-php", the package "https://atom.io/packages/atom-autocomplete-php" stoppes working. I think "atom/ide-php" not working with PHP 7.4 or someone can help me?

Is there some conflict?

**Comment by lkashef** [comment]
Hey @orukaz, Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
