### ISSUE TITLE
Listar funciones de un archivo externo

### ISSUE THREAD

**Issue by Frank-0511** [atom/ide-php#153]
No se si esto va aqui, o en bugs yaq que no estoy muy seguro de que en realidad exista esto, yo estoy usando php con laravel  y tengo por cada controlador su repository que es un archivoen en cual tengo todas mis consultas a base de datos, lo que pasa es que el autocompletar luego de escribir: 
$this->reportRepository-> si le doy control + espacio no me muestra la lista de funcionalidades de mi archivo repository y cuando pongo Helper:: si me muestra la lista pero sin los parametros y tampoco me muestra el bloque documentado donde escribi su logica de funcionamiento y los tipos de datos que ingresan como parametros, esto si lo pude realizar en visualcode.

Gracias, espero puedan ayudarme

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
