### ISSUE TITLE
Use Intelephense language server instead

### ISSUE THREAD

**Issue by junaidbhura** [atom/ide-php#46]
FelixFBeckers Language Server is excruciatingly slow. Perhaps you can try using a much faster one like this:
https://github.com/bmewburn/vscode-intelephense

**Comment by damieng** [comment]
I don't think we're going to switch just yet - we've invested some time and effort getting this far with the current language server and switching it would be taking mostly a reset as a lot of the effort is around getting the server packages downloaded and installed (something the intelephense server would need writing again)

That's not to say somebody else couldn't create an ide-php-intelephense using atom-languageclient.

**Comment by junaidbhura** [comment]
That's too bad @damieng :( . I think now would be a good time to take tough decisions like this, considering this is still a pre-release. Folks already don't take Atom seriously because they find it slow, and this would just give them another reason to hate on it.

**Comment by mikebronner** [comment]
@junaidbhura I understand your frustration, believe me. I have found a good setup that I am currently using that currently still outperforms both VSCode as well as ide-php. I will be using that until ide-php is at a point that it becomes usable for daily development. That is not a criticism of the package, as I can appreciate the complexity involved in creating a package like this, and it takes time to mature. (The main reason I'm not using ide-php is also because of the language server -- my autocomplete package of choice for Atom is atom-autocomplete-php, it works the best and is most complete in detecting installed packages.)

My best suggestion for now is to establish an Atom Editor package list that meets all your needs, and keep evaluating ide-php as it progresses until you find it workable.

I keep a separate config folder for Atom Beta and check in with that every few days to see how progress is coming along and report in if I see any problems, hopefully helping the project maintainers. :)

**Comment by junaidbhura** [comment]
Hey @mikebronner yeah I totally agree with you. I kinda do the same thing, but I'm also slowly starting to move towards PHPStorm, because it's really smart.

I would much rather stay with Atom, because I believe in the philosophy behind it, and I love the way it feels. Unfortunately, I need something much more powerful, and I hope I can come back to Atom some day when it's more powerful!

Kudos to you for helping out by the way 👍

**Comment by mikebronner** [comment]
@junaidbhura I have actually moved away from PHPStorm to Atom, and have been using it for a year now on a daily basis in large Laravel projects. PHPStorm comes with its own set of challenges.

Maybe I can help you out with suggestion for packages that would let you do the things that PHPStorm does? I have actually been able to cover all my developer needs in Atom now, which I relied on PHPStorm for in the past. I plan on putting up a list of packages I use, maybe over the weekend. :) Always short on time. hehe Feel free to email me directly on my github profile if you are interested in discussing this further, probably not the best place for a discussion like that here.

**Comment by junaidbhura** [comment]
Haha @mikebronner sure sounds great! I'd totally be interested to learn what packages you use! DM-ing you now.

**Comment by jens1o** [comment]
Personally, I don't get why it should be slow. Although yes, it is php, but when you activate OPCache and use PHP 7.2, it is extremly fast compared to before. ;)

I think using the language server will increase the speed of it, so, from time to time, we're going to get a faster language server.

**Comment by dcboy95** [comment]
@mikebronner What kind of setup do you have, if you don't mind me asking? I've looked around and used a few plugin's but cant seem to get the perfect autocomplete "intellisense" experience

**Comment by mikebronner** [comment]
Anyone interested in my current daily driver setup, try the following:

You can install my setup using the `sync-settings` package. Then fork my gist (https://gist.github.com/mikebronner/172a6d1e6ea0df3dce316d6dff6faf23) and configure the sync-settings package in Atom. After that, CMD-SHIFT-P and type restore, then select 'Sync Settings: Restore' and it will install all the things for you.

Then every time you tweak your configuration, CMD-SHIFT-P and type 'backup' and select 'Sync Settings: Backup' to save your updated config.

**Comment by rileyrg** [comment]
Just an aside here: I have used language server and intelephense with LSP in Emacs. There is no comparison. intelephense works a lot better/faster. Any work moving to intelephense should be minimal if it adheres to the LSP framework.

**Comment by jens1o** [comment]
However, intelephense is not FOSS. So I don't think this should be included in a package with the current LICENSE.
